version: "2.2"
services:
  jobmanager:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - "./src/main/resources/results:/trendyol_docker/results"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - "./src/main/resources/results:/trendyol_docker/results"
    scale: 1
    links:
      - "jobmanager:jobmanager"
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
